#![allow(
    clippy::expect_used,
    reason = "a build script that cannot read its inputs must fail the build loudly, not paper over it"
)]

//! Embed the web client into the binary.
//!
//! Walked at build time rather than listed by hand: a hand-written list is a
//! second place to remember, and the failure it produces — one module missing
//! from a deployed client — shows up as a blank page, not as a build error.

use std::{env, fs, path::Path};

fn main() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../web/public");
    println!("cargo:rerun-if-changed={}", root.display());

    let mut entries = Vec::new();
    walk(&root, &root, &mut entries);
    entries.sort();

    let mut out = String::from(
        "// @generated by build.rs — the web client, embedded.\n\
         pub(crate) static ASSETS: &[(&str, &str, &[u8])] = &[\n",
    );
    for (route, path) in &entries {
        out.push_str(&format!(
            "    ({route:?}, {:?}, include_bytes!({:?})),\n",
            mime(route),
            path
        ));
    }
    out.push_str("];\n");

    let dest = Path::new(&env::var("OUT_DIR").expect("OUT_DIR")).join("assets.rs");
    fs::write(dest, out).expect("write assets.rs");
}

fn walk(root: &Path, dir: &Path, out: &mut Vec<(String, String)>) {
    let Ok(read) = fs::read_dir(dir) else {
        // No client built. The server still runs and still serves the API —
        // which is what `cargo test` on a fresh clone needs it to do.
        return;
    };
    for entry in read.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk(root, &path, out);
        } else if let Ok(rel) = path.strip_prefix(root) {
            let route = format!("/{}", rel.to_string_lossy().replace('\\', "/"));
            out.push((route, path.to_string_lossy().into_owned()));
        }
    }
}

/// The content type, which is not cosmetic: a browser refuses to execute a
/// module served as `text/plain`, and the page loads with no error anywhere.
fn mime(route: &str) -> &'static str {
    match route.rsplit('.').next() {
        Some("html") => "text/html; charset=utf-8",
        Some("js") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("webmanifest") | Some("json") => "application/manifest+json",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        _ => "application/octet-stream",
    }
}
