[package]
name = "omt-catalog"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
omt-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }
thiserror = { workspace = true }
linkme = { workspace = true }
bitflags = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
schemars = { workspace = true }
omt-types = { workspace = true }
linkme = { workspace = true }
serde = { workspace = true }
